name: Build and Release url-shortener

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Switch to main branch
      run: |
        git checkout main
        git pull origin main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'

    - name: Install Go dependencies
      run: go mod download

    - name: Build Go application
      run: go build -o url-shortener ./cmd/main.go

    - name: Generate CHANGELOG
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "## ${{ github.ref_name }} ($(date '+%Y-%m-%d'))" >> CHANGELOG.md
        echo "- Release for ${{ github.ref_name }}" >> CHANGELOG.md
        git add CHANGELOG.md
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit -m "Update CHANGELOG for ${{ github.ref_name }}"
        git push origin main

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          url-shortener
          front/index.html
          CHANGELOG.md
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}