name: Build url-shortener on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Полная история для генерации CHANGELOG 
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
    
    - name: Install Go dependencies
      run: go mod download

    - name: Build Go application
      run: go build -o url-shortener ./cmd/main.go
    
    - name: Generate CHANGELOG
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "## ${{ github.ref_name }} ($(date '+%Y-%m-%d'))" >> CHANGELOG.md
        echo "- Release for ${{ github.ref_name }}" >> CHANGELOG.md
        git add CHANGELOG.md
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit -m "Update CHANGELOG for ${{ github.ref_name }}"
        git push

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          cmd/main.go
          front/index.html
          config/config.go
          db/postgres.go
          CHANGELOG.md
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}